### PR TITLE
feat: enable material 3 and fix uri permission

### LINKED ISSUE #1: Permission keeps being asked even after granting permission

### LINKED ISSUE #2: During navigation from watching video to back the permission is asked again

### LINKED ISSUE #4: Support for Material You
Hello,
This app would look amazing on Material you.

### PR DESCRIPTION
**Pull request by yogeshpaliyal**
Fixes #4
Fixes #2
Fixes #1

| Light | Dark |
|---------|--------|
|||

### CODE REVIEW

File: app/src/main/java/com/breens/whatsappstatussaver/theme/Theme.kt [hunk 1]
```diff
@@ -84,7 +84,7 @@ private val LightColorScheme = lightColorScheme(
 fun WhatsappStatusSaverTheme(
     darkTheme: Boolean = isSystemInDarkTheme(),
     // Dynamic color is available on Android 12+
-    dynamicColor: Boolean = false,
+    dynamicColor: Boolean = true,
```
Comment (Breens-Mbaka) [inline app/src/main/java/com/breens/whatsappstatussaver/theme/Theme.kt:87]: 👍

File: app/src/main/java/com/breens/whatsappstatussaver/statuses/presentation/StatusesScreen.kt [hunk 2]
```diff
@@ -94,8 +97,18 @@ fun StatusesScreen(
...
+            val mediaDocumentFile = context.getMediaFolder()
+            if (checkIfMediaFolderAccessible(mediaDocumentFile!!)) {
+                viewModel.sendEvent(
+                    event = StatusesScreenUiEvents.GetStatusImages(
+                        uri = mediaDocumentFile.uri,
+                        fromNormalStorage = false
+                    )
+                )
+            } else {
+                val intent = context.mediaFolderIntent(mediaDocumentFile)
```
Comment (Breens-Mbaka) [inline app/src/main/java/com/breens/whatsappstatussaver/statuses/presentation/StatusesScreen.kt:109]: great workaround 👏

File: app/src/main/java/com/breens/whatsappstatussaver/mediafilepermission/AskMediaFolderAccessPermission.kt [hunk 3]
```diff
@@ -10,14 +10,27 @@ import androidx.documentfile.provider.DocumentFile
...
-    val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
-    intent.putExtra(
-        DocumentsContract.EXTRA_INITIAL_URI,
-        DocumentFile.fromTreeUri(
-            this,
-            Uri.parse("content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fmedia%2Fcom.whatsapp%2FWhatsApp%2FMedia%2FStatuses"),
-        )!!.uri,
+fun Context.getMediaFolder(): DocumentFile? {
+    val mediaFolder = DocumentFile.fromTreeUri(
+        this,
```
Comment (Breens-Mbaka) [inline app/src/main/java/com/breens/whatsappstatussaver/mediafilepermission/AskMediaFolderAccessPermission.kt:15]: awesome

**Review by Breens-Mbaka — APPROVED** [review]

**Comment by Breens-Mbaka** [comment]
Awesome work 👏 @yogeshpaliyal . I'll be publishing a new version on the Play Store this week
